/* -*- C++ -*- */
#pragma once

// This file should really contain the definitions for each parameter
// Define other values (globals)

// #define MIDI_Channel_0              * 10 // 0 (omni) or 1 - 16
// #define MIDI_Channel_1              * 11 // 0 (omni) or 1 - 16
// #define LAYER_MODE                  * 12 // 0 Off or 1 On
constexpr int PRM_ALGO0=                  1; // binary based on LSB
constexpr int PRM_ALGO1=                  2; // binary based on LSB
constexpr int PRM_ALGO2=                  3; // binary based on LSB
constexpr int PRM_ALGO3=                  4; // binary based on LSB
constexpr int PRM_ALGO4=                  5; // binary based on LSB
constexpr int PRM_ALGO5=                  6; // binary based on LSB
constexpr int PRM_FEEDBACK0=              7;
constexpr int PRM_FEEDBACK1=              8;
constexpr int PRM_FEEDBACK2=              9;
constexpr int PRM_FEEDBACK3=              10;
constexpr int PRM_FEEDBACK4=              11;
constexpr int PRM_FEEDBACK5=              12;
constexpr int PRM_OSC_SYNC=               13; // bitwise parameter to set each operator to free-run (0) or note-on (1)
constexpr int PRM_OSC_MODE=               14; // binary based on LSB
constexpr int PRM_RATIO0=                 15;
constexpr int PRM_RATIO1=                 16;
constexpr int PRM_RATIO2=                 17;
constexpr int PRM_RATIO3=                 18;
constexpr int PRM_RATIO4=                 19;
constexpr int PRM_RATIO5=                 20;
constexpr int PRM_RATIO_FINE0=            21;
constexpr int PRM_RATIO_FINE1=            22;
constexpr int PRM_RATIO_FINE2=            23;
constexpr int PRM_RATIO_FINE3=            24;
constexpr int PRM_RATIO_FINE4=            25;
constexpr int PRM_RATIO_FINE5=            26;
constexpr int PRM_FINE0=                  27;
constexpr int PRM_FINE1=                  28;
constexpr int PRM_FINE2=                  29;
constexpr int PRM_FINE3=                  30;
constexpr int PRM_FINE4=                  31;
constexpr int PRM_FINE5=                  32;
constexpr int PRM_LEVEL0=                 33;
constexpr int PRM_LEVEL1=                 34;
constexpr int PRM_LEVEL2=                 35;
constexpr int PRM_LEVEL3=                 36;
constexpr int PRM_LEVEL4=                 37;
constexpr int PRM_LEVEL5=                 38;
constexpr int PRM_VEL_SENS0=              39;
constexpr int PRM_VEL_SENS1=              40;
constexpr int PRM_VEL_SENS2=              41;
constexpr int PRM_VEL_SENS3=              42;
constexpr int PRM_VEL_SENS4=              43;
constexpr int PRM_VEL_SENS5=              44;
constexpr int PRM_KEY_BP0=                45;
constexpr int PRM_KEY_BP1=                46;
constexpr int PRM_KEY_BP2=                47;
constexpr int PRM_KEY_BP3=                48;
constexpr int PRM_KEY_BP4=                49;
constexpr int PRM_KEY_BP5=                50;
constexpr int PRM_KEY_LDEPTH0=            51;
constexpr int PRM_KEY_LDEPTH1=            52;
constexpr int PRM_KEY_LDEPTH2=            53;
constexpr int PRM_KEY_LDEPTH3=            54;
constexpr int PRM_KEY_LDEPTH4=            55;
constexpr int PRM_KEY_LDEPTH5=            56;
constexpr int PRM_KEY_RDEPTH0=            57;
constexpr int PRM_KEY_RDEPTH1=            58;
constexpr int PRM_KEY_RDEPTH2=            59;
constexpr int PRM_KEY_RDEPTH3=            60;
constexpr int PRM_KEY_RDEPTH4=            61;
constexpr int PRM_KEY_RDEPTH5=            62;
constexpr int PRM_KEY_LCURVE0=            63; // 0 - 3
constexpr int PRM_KEY_LCURVE1=            64; // 0 - 3
constexpr int PRM_KEY_LCURVE2=            65; // 0 - 3
constexpr int PRM_KEY_LCURVE3=            66; // 0 - 3
constexpr int PRM_KEY_LCURVE4=            67; // 0 - 3
constexpr int PRM_KEY_LCURVE5=            68; // 0 - 3
constexpr int PRM_KEY_RCURVE0=            69; // 0 - 3
constexpr int PRM_KEY_RCURVE1=            70; // 0 - 3
constexpr int PRM_KEY_RCURVE2=            71; // 0 - 3
constexpr int PRM_KEY_RCURVE3=            72; // 0 - 3
constexpr int PRM_KEY_RCURVE4=            73; // 0 - 3
constexpr int PRM_KEY_RCURVE5=            74; // 0 - 3
constexpr int PRM_L1_0=                   75;
constexpr int PRM_L1_1=                   76;
constexpr int PRM_L1_2=                   77;
constexpr int PRM_L1_3=                   78;
constexpr int PRM_L1_4=                   79;
constexpr int PRM_L1_5=                   80;
constexpr int PRM_L2_0=                   82;
constexpr int PRM_L2_1=                   83;
constexpr int PRM_L2_2=                   84;
constexpr int PRM_L2_3=                   85;
constexpr int PRM_L2_4=                   86;
constexpr int PRM_L2_5=                   87;
constexpr int PRM_L3_0=                   89;
constexpr int PRM_L3_1=                   90;
constexpr int PRM_L3_2=                   91;
constexpr int PRM_L3_3=                   92;
constexpr int PRM_L3_4=                   93;
constexpr int PRM_L3_5=                   94;
constexpr int PRM_L4_0=                   96;
constexpr int PRM_L4_1=                   97;
constexpr int PRM_L4_2=                   98;
constexpr int PRM_L4_3=                   99;
constexpr int PRM_L4_4=                   100;
constexpr int PRM_L4_5=                   101;
constexpr int PRM_R1_0=                   103;
constexpr int PRM_R1_1=                   104;
constexpr int PRM_R1_2=                   105;
constexpr int PRM_R1_3=                   106;
constexpr int PRM_R1_4=                   107;
constexpr int PRM_R1_5=                   108;
constexpr int PRM_R2_0=                   110;
constexpr int PRM_R2_1=                   111;
constexpr int PRM_R2_2=                   112;
constexpr int PRM_R2_3=                   113;
constexpr int PRM_R2_4=                   114;
constexpr int PRM_R2_5=                   115;
constexpr int PRM_R3_0=                   117;
constexpr int PRM_R3_1=                   118;
constexpr int PRM_R3_2=                   119;
constexpr int PRM_R3_3=                   120;
constexpr int PRM_R3_4=                   121;
constexpr int PRM_R3_5=                   122;
constexpr int PRM_R4_0=                   124;
constexpr int PRM_R4_1=                   125;
constexpr int PRM_R4_2=                   126;
constexpr int PRM_R4_3=                   127;
constexpr int PRM_R4_4=                   128;
constexpr int PRM_R4_5=                   129;
constexpr int PRM_L1_P=                   130;
constexpr int PRM_L2_P=                   131;
constexpr int PRM_L3_P=                   132;
constexpr int PRM_L4_P=                   133;
constexpr int PRM_R1_P=                   134;
constexpr int PRM_R2_P=                   135;
constexpr int PRM_R3_P=                   136;
constexpr int PRM_R4_P=                   137;
constexpr int PRM_EG_PITCH_RANGE=         138;
constexpr int PRM_EG_PITCH_RANGE_VELO=    139;
constexpr int PRM_RATE_KEY0=              140;
constexpr int PRM_RATE_KEY1=              141;
constexpr int PRM_RATE_KEY2=              142;
constexpr int PRM_RATE_KEY3=              143;
constexpr int PRM_RATE_KEY4=              144;
constexpr int PRM_RATE_KEY5=              145;
constexpr int PRM_RATE_KEYP=              146;
constexpr int PRM_LFO_PITCH_DEPTH=        149;
constexpr int PRM_LFO_AMP_DEPTH=          150;
constexpr int PRM_LFO_SPEED=              151;
constexpr int PRM_LFO_SYNC=               152; // 0 - 3 (single, free running), single, Key sync, Multi, Free running, Multi, Key sync
constexpr int PRM_LFO_WAVE=               153; // 0 - 5 (Triangle, Square, Saw up, Saw Down, Sine, Random)
constexpr int PRM_LFO_FADE=               154;
constexpr int PRM_LFO_PITCH_DEPTH_WHEEL=  155;
constexpr int PRM_LFO_AMP_DEPTH_WHEEL=    156;
constexpr int PRM_LFO_PITCH_DEPTH_AFTER=  157;
constexpr int PRM_LFO_AMP_DEPTH_AFTER=    158;
constexpr int PRM_LFO_AMS0=               159;
constexpr int PRM_LFO_AMS1=               160;
constexpr int PRM_LFO_AMS2=               161;
constexpr int PRM_LFO_AMS3=               162;
constexpr int PRM_LFO_AMS4=               163;
constexpr int PRM_LFO_AMS5=               164;
constexpr int PRM_BEND_RANGE_UP=          172;
constexpr int PRM_BEND_RANGE_DN=          173;
constexpr int PRM_TRANSPOSE=              174; // center value is 24 (no transpose)
constexpr int PRM_VOLUME=                 180;
constexpr int PRM_L0_0=                   181;
constexpr int PRM_L0_1=                   182;
constexpr int PRM_L0_2=                   183;
constexpr int PRM_L0_3=                   184;
constexpr int PRM_L0_4=                   185;
constexpr int PRM_L0_5=                   186;
constexpr int PRM_R0_0=                   187;
constexpr int PRM_R0_1=                   188;
constexpr int PRM_R0_2=                   189;
constexpr int PRM_R0_3=                   190;
constexpr int PRM_R0_4=                   191;
constexpr int PRM_R0_5=                   192;
constexpr int PRM_L5_0=                   193;
constexpr int PRM_L5_1=                   194;
constexpr int PRM_L5_2=                   195;
constexpr int PRM_L5_3=                   196;
constexpr int PRM_L5_4=                   197;
constexpr int PRM_L5_5=                   198;
constexpr int PRM_R5_0=                   199;
constexpr int PRM_R5_1=                   200;
constexpr int PRM_R5_2=                   201;
constexpr int PRM_R5_3=                   202;
constexpr int PRM_R5_4=                   203;
constexpr int PRM_R5_5=                   204;
constexpr int PRM_L0_P=                   205;
constexpr int PRM_R0_P=                   206;
constexpr int PRM_L5_P=                   207;
constexpr int PRM_R5_P=                   208;
constexpr int PRM_LFO_PITCH_DEPTH_BREATH= 209;
constexpr int PRM_LFO_AMP_DEPTH_BREATH=   210;
constexpr int PRM_LFO_PITCH_DEPTH_FOOT=   211;
constexpr int PRM_LFO_AMP_DEPTH_FOOT=     212;
constexpr int PRM_VOLUME_DEPTH_AFTER=     213;
constexpr int PRM_VOLUME_DEPTH_WHEEL=     214;
constexpr int PRM_VOLUME_DEPTH_BREATH=    215;
constexpr int PRM_VOLUME_DEPTH_FOOT=      216;
constexpr int PRM_PITCH_DEPTH_AFTER=      217;
constexpr int PRM_PITCH_DEPTH_BREATH=     218;
constexpr int PRM_PITCH_DEPTH_FOOT=       219;
constexpr int PRM_PITCH_DEPTH_RND=        220;
constexpr int PRM_PAN=                    221;
constexpr int PRM_LFO_PMS0=               222;
constexpr int PRM_LFO_PMS1=               223;
constexpr int PRM_LFO_PMS2=               224;
constexpr int PRM_LFO_PMS3=               225;
constexpr int PRM_LFO_PMS4=               226;
constexpr int PRM_LFO_PMS5=               227;
constexpr int PRM_LEGATO=                 228; // 0 - 1 (Polyphonic 0 or Monophonic Legato (1))
constexpr int PRM_PORTA_MODE=             229; // 0 - 2 (0 off, 1 always, 2 fingered)
constexpr int PRM_PORTA_TIME=             230;
constexpr int PRM_WAVEFORM0=              236; // 0 - 7
constexpr int PRM_WAVEFORM1=              237; // 0 - 7
constexpr int PRM_WAVEFORM2=              238; // 0 - 7
constexpr int PRM_WAVEFORM3=              239; // 0 - 7
constexpr int PRM_WAVEFORM4=              240; // 0 - 7
constexpr int PRM_WAVEFORM5=              241; // 0 - 7
constexpr int PRM_VELO_OFFSET=            242;
constexpr int PRM_VELO_CURVE=             243;
constexpr int PRM_EG_LOOP=                244; // bitwise
constexpr int PRM_EG_LOOP_SEG=            245; // bitwise
constexpr int PRM_EG_RESTART=             246;
constexpr int PRM_TUNING=                 251;
constexpr int PRM_LEVEL0_L=               256;
constexpr int PRM_LEVEL0_R=               257;
constexpr int PRM_LEVEL1_L=               258;
constexpr int PRM_LEVEL1_R=               259;
constexpr int PRM_LEVEL2_L=               260;
constexpr int PRM_LEVEL2_R=               261;
constexpr int PRM_LEVEL3_L=               262;
constexpr int PRM_LEVEL3_R=               263;
constexpr int PRM_LEVEL4_L=               264;
constexpr int PRM_LEVEL4_R=               265;
constexpr int PRM_LEVEL5_L=               266;
constexpr int PRM_LEVEL5_R=               267;
constexpr int PRM_WAVEFORM2_0=            268; // 0 - 7
constexpr int PRM_WAVEFORM2_1=            269; // 0 - 7
constexpr int PRM_WAVEFORM2_2=            270; // 0 - 7
constexpr int PRM_WAVEFORM2_3=            271; // 0 - 7
constexpr int PRM_WAVEFORM2_4=            272; // 0 - 7
constexpr int PRM_WAVEFORM2_5=            273; // 0 - 7
constexpr int PRM_WMODE0=                 274; // 0 - 1
constexpr int PRM_WMODE1=                 275; // 0 - 1
constexpr int PRM_WMODE2=                 276; // 0 - 1
constexpr int PRM_WMODE3=                 277; // 0 - 1
constexpr int PRM_WMODE4=                 278; // 0 - 1
constexpr int PRM_WMODE5=                 279; // 0 - 1
constexpr int PRM_WRATIO0=                280;
constexpr int PRM_WRATIO1=                281;
constexpr int PRM_WRATIO2=                282;
constexpr int PRM_WRATIO3=                283;
constexpr int PRM_WRATIO4=                284;
constexpr int PRM_WRATIO5=                285;
constexpr int PRM_OSC_PHASE0=             286; // 0 - 3 (0 / 90 / 180 / 270)
constexpr int PRM_OSC_PHASE1=             287; // 0 - 3 (0 / 90 / 180 / 270)
constexpr int PRM_OSC_PHASE2=             288; // 0 - 3 (0 / 90 / 180 / 270)
constexpr int PRM_OSC_PHASE3=             289; // 0 - 3 (0 / 90 / 180 / 270)
constexpr int PRM_OSC_PHASE4=             290; // 0 - 3 (0 / 90 / 180 / 270)
constexpr int PRM_OSC_PHASE5=             291; // 0 - 3 (0 / 90 / 180 / 270)
constexpr int PRM_SDLY_DRY=               300;
constexpr int PRM_SDLY_WET=               301;
constexpr int PRM_SDLY_MODE=              302; // 0 - 3 Stereo, Cross, Bounce
constexpr int PRM_SDLY_TIME=              303;
constexpr int PRM_SDLY_FEEDBACK=          304;
constexpr int PRM_SDLY_FEEDLO=            305;
constexpr int PRM_SDLY_FEEDHI=            306;
constexpr int PRM_SDLY_TEMPO=             307; // 0 midi, 50-255
constexpr int PRM_SDLY_NUM=               308;
constexpr int PRM_SDLY_DEN=               309;
constexpr int PRM_PHASER_DRY=             310;
constexpr int PRM_PHASER_WET=             311;
constexpr int PRM_PHASER_MODE=            312; // 0 - 2 (Mono, Stereo, Cross)
constexpr int PRM_PHASER_DEPTH=           313;
constexpr int PRM_PHASER_SPEED=           314;
constexpr int PRM_PHASER_FEEDBACK=        315;
constexpr int PRM_PHASER_OFFSET=          316;
constexpr int PRM_PHASER_STAGES=          317; // 4-12?
constexpr int PRM_PHASER_PHASE=           318;
constexpr int PRM_PHASER_WAVEFORM=        319;
constexpr int PRM_FILTER_LO=              320;
constexpr int PRM_FILTER_HI=              321;
constexpr int PRM_AM_SPEED=               330;
constexpr int PRM_AM_RANGE=               331;
constexpr int PRM_AM_DEPTH=               332;
constexpr int PRM_AM_PHASE=               333;
constexpr int PRM_FIR_IMPULSE=            340;
constexpr int PRM_WAVESHAPER_DRY=         350;
constexpr int PRM_WAVESHAPER_WET=         351;
constexpr int PRM_WAVESHAPER_GAIN_PRE=    352;
constexpr int PRM_WAVESHAPER_GAIN_POST=   353;
constexpr int PRM_WAVESHAPER_SHAPE=       354;
constexpr int PRM_CHORUS_DRY=             360;
constexpr int PRM_CHORUS_WET=             361;
constexpr int PRM_CHORUS_MODE=            362; // 0 - 3 (Chorus long, Chorus Short, Flanger Long, Flanger Short)
constexpr int PRM_CHORUS_SPEED=           363;
constexpr int PRM_CHORUS_DEPTH=           364;
constexpr int PRM_CHORUS_FEEDBACK=        365;
constexpr int PRM_CHORUS_PHASE=           366;
constexpr int PRM_DECIMATOR_DEPTH=        370;
constexpr int PRM_BITCRUSHER_DEPTH=       380; // 0 - 24 (bits to reduce)
constexpr int PRM_REVERB_DRY=             390;
constexpr int PRM_REVERB_WET=             391;
constexpr int PRM_REVERB_MODE=            392; // 0 - 1 Plate or Hall
constexpr int PRM_REVERB_DECAY=           393;
constexpr int PRM_REVERB_DAMP=            394;
constexpr int PRM_REVERB_D0=              395;
constexpr int PRM_REVERB_D1=              396;
constexpr int PRM_REVERB_D2=              397;
constexpr int PRM_FX_ROUTING=             410; // 0 or 1
constexpr int PRM_OUTPUT_LEVEL=           411;
constexpr int PRM_GAIN_LEVEL=             412; // 0, 1 , 2, 3
constexpr int PRM_CONTROL_1H=             420;
constexpr int PRM_CONTROL_1L=             421;
constexpr int PRM_CONTROL_2H=             422;
constexpr int PRM_CONTROL_2L=             423;
constexpr int PRM_CONTROL_3H=             424;
constexpr int PRM_CONTROL_3L=             425;
constexpr int PRM_CONTROL_4H=             426;
constexpr int PRM_CONTROL_4L=             427;
constexpr int PRM_ARP_MODE=               450; // 0 - 5 (Off, Up, Down, Up/Down, As Played, Random)
constexpr int PRM_ARP_TEMPO=              451; // 0 is midi sync, 50-255
constexpr int PRM_ARP_TEMPO_FINE=         452;
constexpr int PRM_ARP_DIVISION=           453;
constexpr int PRM_ARP_OCTAVES=            454;
